const CELL_SIZE = 50;
const PLAYER_SIZE = 10;
const PLAYER_HEIGHT = 50;
const PLAYER_SPEED = 150;
const GRAVITY = 300;
const JUMP_FORCE = 130;
const MAX_FALL_SPEED = 320;

export { CELL_SIZE, PLAYER_SIZE, PLAYER_HEIGHT, PLAYER_SPEED, GRAVITY, JUMP_FORCE, MAX_FALL_SPEED };