const CELL_SIZE = 20;
const CELL_PADDING = 3;
const REAL_CELL_SIZE = CELL_SIZE - 2 * CELL_PADDING;
const BORDER_WIDTH = 2;
const PLAYER_SIZE = 20;

export { CELL_SIZE, CELL_PADDING, REAL_CELL_SIZE, BORDER_WIDTH, PLAYER_SIZE };