const CELL_SIZE = 20;
const PLAYER_SIZE = 2;
const PLAYER_HEIGHT = 50;
const PLAYER_SPEED = 300;
const GRAVITY = 380;
const JUMP_FORCE = 200;
const MAX_FALL_SPEED = 320;

export { CELL_SIZE, PLAYER_SIZE, PLAYER_HEIGHT, PLAYER_SPEED, GRAVITY, JUMP_FORCE, MAX_FALL_SPEED };